# Generated by Django 4.1.6 on 2023-12-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'variations', 'verbose_name_plural': 'متغیرها '},
        ),
    ]
