# Generated by Django 4.2.7 on 2024-01-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'گالری محصول'},
        ),
        migrations.RenameField(
            model_name='productgallery',
            old_name='produc',
            new_name='product',
        ),
    ]
