# Generated by Django 4.2.7 on 2024-01-10 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'reviewrating', 'verbose_name_plural': 'بررسی نظرسنجی'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'variations', 'verbose_name_plural': 'آیتم متغیر محصول'},
        ),
    ]
