# Generated by Django 4.2.7 on 2024-01-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_meta_description_product_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
