# Generated by Django 4.2.7 on 2024-01-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300)),
                ('details', models.ManyToManyField(related_name='product_detail', to='store.productdetail')),
            ],
        ),
    ]
