# Generated by Django 4.2.7 on 2024-01-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productdetail_productdetailslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='info',
        ),
        migrations.AddField(
            model_name='product',
            name='product_detail',
            field=models.ManyToManyField(to='store.productdetail'),
        ),
    ]
