# Generated by Django 4.2.7 on 2024-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailslist',
            name='details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_detail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_description',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'رنگ'), ('weight', 'مقدار')], max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
        migrations.DeleteModel(
            name='ProductDetailsList',
        ),
    ]
