# Generated by Django 4.2.7 on 2024-02-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
