# Generated by Django 4.2.7 on 2024-01-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
