# Generated by Django 4.2.7 on 2024-01-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_address_line_2_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'orderproduct', 'verbose_name_plural': 'سفارش محصول '},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'پرداختها'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
